# Comprehensive symbols file starting with essentials

# ASCII Basic Latin (Essential)
U + 0020  # SPACE
  U + 0021  # EXCLAMATION MARK
  U + 0022  # QUOTATION MARK
  U + 0023  # NUMBER SIGN
  U + 0024  # DOLLAR SIGN
  U + 0025  # PERCENT SIGN
  U + 0026  # AMPERSAND
  U + 0027  # APOSTROPHE
  U + 0028  # LEFT PARENTHESIS
  U + 0029  # RIGHT PARENTHESIS
  U + 002 A  # ASTERISK
  U + 002 B  # PLUS SIGN
  U + 002 C  # COMMA
  U + 002 D  # HYPHEN-MINUS
  U + 002 E  # FULL STOP
  U + 002 F  # SOLIDUS
  # Numbers
  U + 0030  # DIGIT ZERO
  U + 0031  # DIGIT ONE
  U + 0032  # DIGIT TWO
  U + 0033  # DIGIT THREE
  U + 0034  # DIGIT FOUR
  U + 0035  # DIGIT FIVE
  U + 0036  # DIGIT SIX
  U + 0037  # DIGIT SEVEN
  U + 0038  # DIGIT EIGHT
  U + 0039  # DIGIT NINE
  # Upper case Latin
  U + 0041  # LATIN CAPITAL LETTER A
  U + 0042  # LATIN CAPITAL LETTER B
  U + 0043  # LATIN CAPITAL LETTER C
  U + 0044  # LATIN CAPITAL LETTER D
  U + 0045  # LATIN CAPITAL LETTER E
  U + 0046  # LATIN CAPITAL LETTER F
  U + 0047  # LATIN CAPITAL LETTER G
  U + 0048  # LATIN CAPITAL LETTER H
  U + 0049  # LATIN CAPITAL LETTER I
  U + 004 A  # LATIN CAPITAL LETTER J
  U + 004 B  # LATIN CAPITAL LETTER K
  U + 004 C  # LATIN CAPITAL LETTER L
  U + 004 D  # LATIN CAPITAL LETTER M
  U + 004 E  # LATIN CAPITAL LETTER N
  U + 004 F  # LATIN CAPITAL LETTER O
  U + 0050  # LATIN CAPITAL LETTER P
  U + 0051  # LATIN CAPITAL LETTER Q
  U + 0052  # LATIN CAPITAL LETTER R
  U + 0053  # LATIN CAPITAL LETTER S
  U + 0054  # LATIN CAPITAL LETTER T
  U + 0055  # LATIN CAPITAL LETTER U
  U + 0056  # LATIN CAPITAL LETTER V
  U + 0057  # LATIN CAPITAL LETTER W
  U + 0058  # LATIN CAPITAL LETTER X
  U + 0059  # LATIN CAPITAL LETTER Y
  U + 005 A  # LATIN CAPITAL LETTER Z
  # Math and Programming Symbols
  U + 003 A  # COLON
  U + 003 B  # SEMICOLON
  U + 003 C  # LESS-THAN SIGN
  U + 003 D  # EQUALS SIGN
  U + 003 E  # GREATER-THAN SIGN
  U + 003 F  # QUESTION MARK
  U + 0040  # COMMERCIAL AT
  # Lower case Latin
  U + 0061  # LATIN SMALL LETTER A
  U + 0062  # LATIN SMALL LETTER B
  U + 0063  # LATIN SMALL LETTER C
  U + 0064  # LATIN SMALL LETTER D
  U + 0065  # LATIN SMALL LETTER E
  U + 0066  # LATIN SMALL LETTER F
  U + 0067  # LATIN SMALL LETTER G
  U + 0068  # LATIN SMALL LETTER H
  U + 0069  # LATIN SMALL LETTER I
  U + 006 A  # LATIN SMALL LETTER J
  U + 006 B  # LATIN SMALL LETTER K
  U + 006 C  # LATIN SMALL LETTER L
  U + 006 D  # LATIN SMALL LETTER M
  U + 006 E  # LATIN SMALL LETTER N
  U + 006 F  # LATIN SMALL LETTER O
  U + 0070  # LATIN SMALL LETTER P
  U + 0071  # LATIN SMALL LETTER Q
  U + 0072  # LATIN SMALL LETTER R
  U + 0073  # LATIN SMALL LETTER S
  U + 0074  # LATIN SMALL LETTER T
  U + 0075  # LATIN SMALL LETTER U
  U + 0076  # LATIN SMALL LETTER V
  U + 0077  # LATIN SMALL LETTER W
  U + 0078  # LATIN SMALL LETTER X
  U + 0079  # LATIN SMALL LETTER Y
  U + 007 A  # LATIN SMALL LETTER Z
  # Programming brackets and symbols
  U + 005 B  # LEFT SQUARE BRACKET
  U + 005 C  # REVERSE SOLIDUS
  U + 005 D  # RIGHT SQUARE BRACKET
  U + 005 E  # CIRCUMFLEX ACCENT
  U + 005 F  # LOW LINE
  U + 0060  # GRAVE ACCENT
  U + 007 B  # LEFT CURLY BRACKET
  U + 007 C  # VERTICAL LINE
  U + 007 D  # RIGHT CURLY BRACKET
  U + 007 E  # TILDE

  # Extended Part 2 - Mathematical Greek and Essential Cyrillic
  # Greek Letters (Mathematical and Scientific)
  U + 0391  # GREEK CAPITAL LETTER ALPHA
  U + 0392  # GREEK CAPITAL LETTER BETA
  U + 0393  # GREEK CAPITAL LETTER GAMMA
  U + 0394  # GREEK CAPITAL LETTER DELTA
  U + 0395  # GREEK CAPITAL LETTER EPSILON
  U + 0396  # GREEK CAPITAL LETTER ZETA
  U + 0397  # GREEK CAPITAL LETTER ETA
  U + 0398  # GREEK CAPITAL LETTER THETA
  U + 0399  # GREEK CAPITAL LETTER IOTA
  U + 039 A  # GREEK CAPITAL LETTER KAPPA
  U + 039 B  # GREEK CAPITAL LETTER LAMDA
  U + 039 C  # GREEK CAPITAL LETTER MU
  U + 039 D  # GREEK CAPITAL LETTER NU
  U + 039 E  # GREEK CAPITAL LETTER XI
  U + 039 F  # GREEK CAPITAL LETTER OMICRON
  U + 03 A0  # GREEK CAPITAL LETTER PI
  U + 03 A1  # GREEK CAPITAL LETTER RHO
  U + 03 A3  # GREEK CAPITAL LETTER SIGMA
  U + 03 A4  # GREEK CAPITAL LETTER TAU
  U + 03 A5  # GREEK CAPITAL LETTER UPSILON
  U + 03 A6  # GREEK CAPITAL LETTER PHI
  U + 03 A7  # GREEK CAPITAL LETTER CHI
  U + 03 A8  # GREEK CAPITAL LETTER PSI
  U + 03 A9  # GREEK CAPITAL LETTER OMEGA

  # Greek Lowercase (Essential for Math/Science)
  U + 03 B1  # GREEK SMALL LETTER ALPHA
  U + 03 B2  # GREEK SMALL LETTER BETA
  U + 03 B3  # GREEK SMALL LETTER GAMMA
  U + 03 B4  # GREEK SMALL LETTER DELTA
  U + 03 B5  # GREEK SMALL LETTER EPSILON
  U + 03 B6  # GREEK SMALL LETTER ZETA
  U + 03 B7  # GREEK SMALL LETTER ETA
  U + 03 B8  # GREEK SMALL LETTER THETA
  U + 03 B9  # GREEK SMALL LETTER IOTA
  U + 03 BA  # GREEK SMALL LETTER KAPPA
  U + 03 BB  # GREEK SMALL LETTER LAMDA
  U + 03 BC  # GREEK SMALL LETTER MU
  U + 03 BD  # GREEK SMALL LETTER NU
  U + 03 BE  # GREEK SMALL LETTER XI
  U + 03 BF  # GREEK SMALL LETTER OMICRON
  U + 03 C0  # GREEK SMALL LETTER PI
  U + 03 C1  # GREEK SMALL LETTER RHO
  U + 03 C2  # GREEK SMALL LETTER FINAL SIGMA
  U + 03 C3  # GREEK SMALL LETTER SIGMA
  U + 03 C4  # GREEK SMALL LETTER TAU
  U + 03 C5  # GREEK SMALL LETTER UPSILON
  U + 03 C6  # GREEK SMALL LETTER PHI
  U + 03 C7  # GREEK SMALL LETTER CHI
  U + 03 C8  # GREEK SMALL LETTER PSI
  U + 03 C9  # GREEK SMALL LETTER OMEGA

  # Essential Cyrillic
  U + 0410  # CYRILLIC CAPITAL LETTER A
  U + 0411  # CYRILLIC CAPITAL LETTER BE
  U + 0412  # CYRILLIC CAPITAL LETTER VE
  U + 0413  # CYRILLIC CAPITAL LETTER GHE
  U + 0414  # CYRILLIC CAPITAL LETTER DE
  U + 0415  # CYRILLIC CAPITAL LETTER IE
  U + 0416  # CYRILLIC CAPITAL LETTER ZHE
  U + 0417  # CYRILLIC CAPITAL LETTER ZE
  U + 0418  # CYRILLIC CAPITAL LETTER I
  U + 0419  # CYRILLIC CAPITAL LETTER SHORT I
  U + 041 A  # CYRILLIC CAPITAL LETTER KA
  U + 041 B  # CYRILLIC CAPITAL LETTER EL
  U + 041 C  # CYRILLIC CAPITAL LETTER EM
  U + 041 D  # CYRILLIC CAPITAL LETTER EN
  U + 041 E  # CYRILLIC CAPITAL LETTER O
  U + 041 F  # CYRILLIC CAPITAL LETTER PE
  U + 0420  # CYRILLIC CAPITAL LETTER ER
  U + 0421  # CYRILLIC CAPITAL LETTER ES
  U + 0422  # CYRILLIC CAPITAL LETTER TE
  U + 0423  # CYRILLIC CAPITAL LETTER U
  U + 0424  # CYRILLIC CAPITAL LETTER EF
  U + 0425  # CYRILLIC CAPITAL LETTER HA
  U + 0426  # CYRILLIC CAPITAL LETTER TSE
  U + 0427  # CYRILLIC CAPITAL LETTER CHE
  U + 0428  # CYRILLIC CAPITAL LETTER SHA
  U + 0429  # CYRILLIC CAPITAL LETTER SHCHA
  U + 042 A  # CYRILLIC CAPITAL LETTER HARD SIGN
  U + 042 B  # CYRILLIC CAPITAL LETTER YERU
  U + 042 C  # CYRILLIC CAPITAL LETTER SOFT SIGN
  U + 042 D  # CYRILLIC CAPITAL LETTER E
  U + 042 E  # CYRILLIC CAPITAL LETTER YU
  U + 042 F  # CYRILLIC CAPITAL LETTER YA

  # Essential Mathematical Operators and Symbols
  U + 2200  # FOR ALL
  U + 2201  # COMPLEMENT
  U + 2202  # PARTIAL DIFFERENTIAL
  U + 2203  # THERE EXISTS
  U + 2204  # THERE DOES NOT EXIST
  U + 2205  # EMPTY SET
  U + 2206  # INCREMENT
  U + 2207  # NABLA
  U + 2208  # ELEMENT OF
  U + 2209  # NOT AN ELEMENT OF
  U + 220 A  # SMALL ELEMENT OF
  U + 220 B  # CONTAINS AS MEMBER
  U + 220 C  # DOES NOT CONTAIN AS MEMBER
  U + 220 D  # SMALL CONTAINS AS MEMBER
  U + 220 E  # END OF PROOF
  U + 220 F  # N-ARY PRODUCT
  U + 2210  # N-ARY COPRODUCT
  U + 2211  # N-ARY SUMMATION
  U + 2212  # MINUS SIGN
  U + 2213  # MINUS-OR-PLUS SIGN
  U + 2214  # DOT PLUS
  U + 2215  # DIVISION SLASH
  U + 2216  # SET MINUS
  U + 2217  # ASTERISK OPERATOR
  U + 2218  # RING OPERATOR
  U + 2219  # BULLET OPERATOR
  U + 221 A  # SQUARE ROOT
  U + 221 B  # CUBE ROOT
  U + 221 C  # FOURTH ROOT
  U + 221 D  # PROPORTIONAL TO
  U + 221 E  # INFINITY

  # Part 3 - Japanese Kana and Box Drawing
  # Japanese Hiragana
  U + 3041  # HIRAGANA LETTER SMALL A
  U + 3042  # HIRAGANA LETTER A
  U + 3043  # HIRAGANA LETTER SMALL I
  U + 3044  # HIRAGANA LETTER I
  U + 3045  # HIRAGANA LETTER SMALL U
  U + 3046  # HIRAGANA LETTER U
  U + 3047  # HIRAGANA LETTER SMALL E
  U + 3048  # HIRAGANA LETTER E
  U + 3049  # HIRAGANA LETTER SMALL O
  U + 304 A  # HIRAGANA LETTER O
  U + 304 B  # HIRAGANA LETTER KA
  U + 304 C  # HIRAGANA LETTER GA
  U + 304 D  # HIRAGANA LETTER KI
  U + 304 E  # HIRAGANA LETTER GI
  U + 304 F  # HIRAGANA LETTER KU
  U + 3050  # HIRAGANA LETTER GU
  U + 3051  # HIRAGANA LETTER KE
  U + 3052  # HIRAGANA LETTER GE
  U + 3053  # HIRAGANA LETTER KO
  U + 3054  # HIRAGANA LETTER GO
  U + 3055  # HIRAGANA LETTER SA
  U + 3056  # HIRAGANA LETTER ZA
  U + 3057  # HIRAGANA LETTER SHI
  U + 3058  # HIRAGANA LETTER ZI
  U + 3059  # HIRAGANA LETTER SU
  U + 305 A  # HIRAGANA LETTER ZU
  U + 305 B  # HIRAGANA LETTER SE
  U + 305 C  # HIRAGANA LETTER ZE
  U + 305 D  # HIRAGANA LETTER SO
  U + 305 E  # HIRAGANA LETTER ZO
  U + 305 F  # HIRAGANA LETTER TA
  U + 3060  # HIRAGANA LETTER DA
  U + 3061  # HIRAGANA LETTER CHI
  U + 3062  # HIRAGANA LETTER DI
  U + 3063  # HIRAGANA LETTER SMALL TSU
  U + 3064  # HIRAGANA LETTER TSU
  U + 3065  # HIRAGANA LETTER DU
  U + 3066  # HIRAGANA LETTER TE
  U + 3067  # HIRAGANA LETTER DE
  U + 3068  # HIRAGANA LETTER TO
  U + 3069  # HIRAGANA LETTER DO
  U + 306 A  # HIRAGANA LETTER NA
  U + 306 B  # HIRAGANA LETTER NI
  U + 306 C  # HIRAGANA LETTER NU
  U + 306 D  # HIRAGANA LETTER NE
  U + 306 E  # HIRAGANA LETTER NO
  U + 306 F  # HIRAGANA LETTER HA
  U + 3070  # HIRAGANA LETTER BA
  U + 3071  # HIRAGANA LETTER PA
  U + 3072  # HIRAGANA LETTER HI
  U + 3073  # HIRAGANA LETTER BI
  U + 3074  # HIRAGANA LETTER PI
  U + 3075  # HIRAGANA LETTER HU
  U + 3076  # HIRAGANA LETTER BU
  U + 3077  # HIRAGANA LETTER PU
  U + 3078  # HIRAGANA LETTER HE
  U + 3079  # HIRAGANA LETTER BE
  U + 307 A  # HIRAGANA LETTER PE
  U + 307 B  # HIRAGANA LETTER HO
  U + 307 C  # HIRAGANA LETTER BO
  U + 307 D  # HIRAGANA LETTER PO
  U + 307 E  # HIRAGANA LETTER MA
  U + 307 F  # HIRAGANA LETTER MI
  U + 3080  # HIRAGANA LETTER MU
  U + 3081  # HIRAGANA LETTER ME
  U + 3082  # HIRAGANA LETTER MO
  U + 3083  # HIRAGANA LETTER SMALL YA
  U + 3084  # HIRAGANA LETTER YA
  U + 3085  # HIRAGANA LETTER SMALL YU
  U + 3086  # HIRAGANA LETTER YU
  U + 3087  # HIRAGANA LETTER SMALL YO
  U + 3088  # HIRAGANA LETTER YO
  U + 3089  # HIRAGANA LETTER RA
  U + 308 A  # HIRAGANA LETTER RI
  U + 308 B  # HIRAGANA LETTER RU
  U + 308 C  # HIRAGANA LETTER RE
  U + 308 D  # HIRAGANA LETTER RO
  U + 308 E  # HIRAGANA LETTER SMALL WA
  U + 308 F  # HIRAGANA LETTER WA
  U + 3090  # HIRAGANA LETTER WI
  U + 3091  # HIRAGANA LETTER WE
  U + 3092  # HIRAGANA LETTER WO
  U + 3093  # HIRAGANA LETTER N
  U + 3094  # HIRAGANA LETTER VU
  U + 3095  # HIRAGANA LETTER SMALL KA
  U + 3096  # HIRAGANA LETTER SMALL KE
  U + 3099  # COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK
  U + 309 A  # COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  U + 309 B  # KATAKANA-HIRAGANA VOICED SOUND MARK
  U + 309 C  # KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  U + 309 D  # HIRAGANA ITERATION MARK
  U + 309 E  # HIRAGANA VOICED ITERATION MARK
  U + 309 F  # HIRAGANA DIGRAPH YORI

  # Box Drawing (Essential for TUI)
  U + 2500  # BOX DRAWINGS LIGHT HORIZONTAL
  U + 2501  # BOX DRAWINGS HEAVY HORIZONTAL
  U + 2502  # BOX DRAWINGS LIGHT VERTICAL
  U + 2503  # BOX DRAWINGS HEAVY VERTICAL
  U + 2504  # BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  U + 2505  # BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
  U + 2506  # BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
  U + 2507  # BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
  U + 2508  # BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
  U + 2509  # BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
  U + 250 A  # BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
  U + 250 B  # BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
  U + 250 C  # BOX DRAWINGS LIGHT DOWN AND RIGHT
  U + 250 D  # BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
  U + 250 E  # BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
  U + 250 F  # BOX DRAWINGS HEAVY DOWN AND RIGHT
  U + 2510  # BOX DRAWINGS LIGHT DOWN AND LEFT
  U + 2511  # BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
  U + 2512  # BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
  U + 2513  # BOX DRAWINGS HEAVY DOWN AND LEFT
  U + 2514  # BOX DRAWINGS LIGHT UP AND RIGHT
  U + 2515  # BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
  U + 2516  # BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
  U + 2517  # BOX DRAWINGS HEAVY UP AND RIGHT
  U + 2518  # BOX DRAWINGS LIGHT UP AND LEFT
  U + 2519  # BOX DRAWINGS UP LIGHT AND LEFT HEAVY
  U + 251 A  # BOX DRAWINGS UP HEAVY AND LEFT LIGHT
  U + 251 B  # BOX DRAWINGS HEAVY UP AND LEFT
  U + 251 C  # BOX DRAWINGS LIGHT VERTICAL AND RIGHT
  U + 251 D  # BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY

  # Part 3 - Japanese Kana and Box Drawing
  # Japanese Hiragana
  U + 3041  # HIRAGANA LETTER SMALL A
  U + 3042  # HIRAGANA LETTER A
  U + 3043  # HIRAGANA LETTER SMALL I
  U + 3044  # HIRAGANA LETTER I
  U + 3045  # HIRAGANA LETTER SMALL U
  U + 3046  # HIRAGANA LETTER U
  U + 3047  # HIRAGANA LETTER SMALL E
  U + 3048  # HIRAGANA LETTER E
  U + 3049  # HIRAGANA LETTER SMALL O
  U + 304 A  # HIRAGANA LETTER O
  U + 304 B  # HIRAGANA LETTER KA
  U + 304 C  # HIRAGANA LETTER GA
  U + 304 D  # HIRAGANA LETTER KI
  U + 304 E  # HIRAGANA LETTER GI
  U + 304 F  # HIRAGANA LETTER KU
  U + 3050  # HIRAGANA LETTER GU
  U + 3051  # HIRAGANA LETTER KE
  U + 3052  # HIRAGANA LETTER GE
  U + 3053  # HIRAGANA LETTER KO
  U + 3054  # HIRAGANA LETTER GO
  U + 3055  # HIRAGANA LETTER SA
  U + 3056  # HIRAGANA LETTER ZA
  U + 3057  # HIRAGANA LETTER SHI
  U + 3058  # HIRAGANA LETTER ZI
  U + 3059  # HIRAGANA LETTER SU
  U + 305 A  # HIRAGANA LETTER ZU
  U + 305 B  # HIRAGANA LETTER SE
  U + 305 C  # HIRAGANA LETTER ZE
  U + 305 D  # HIRAGANA LETTER SO
  U + 305 E  # HIRAGANA LETTER ZO
  U + 305 F  # HIRAGANA LETTER TA
  U + 3060  # HIRAGANA LETTER DA
  U + 3061  # HIRAGANA LETTER CHI
  U + 3062  # HIRAGANA LETTER DI
  U + 3063  # HIRAGANA LETTER SMALL TSU
  U + 3064  # HIRAGANA LETTER TSU
  U + 3065  # HIRAGANA LETTER DU
  U + 3066  # HIRAGANA LETTER TE
  U + 3067  # HIRAGANA LETTER DE
  U + 3068  # HIRAGANA LETTER TO
  U + 3069  # HIRAGANA LETTER DO
  U + 306 A  # HIRAGANA LETTER NA
  U + 306 B  # HIRAGANA LETTER NI
  U + 306 C  # HIRAGANA LETTER NU
  U + 306 D  # HIRAGANA LETTER NE
  U + 306 E  # HIRAGANA LETTER NO
  U + 306 F  # HIRAGANA LETTER HA
  U + 3070  # HIRAGANA LETTER BA
  U + 3071  # HIRAGANA LETTER PA
  U + 3072  # HIRAGANA LETTER HI
  U + 3073  # HIRAGANA LETTER BI
  U + 3074  # HIRAGANA LETTER PI
  U + 3075  # HIRAGANA LETTER HU
  U + 3076  # HIRAGANA LETTER BU
  U + 3077  # HIRAGANA LETTER PU
  U + 3078  # HIRAGANA LETTER HE
  U + 3079  # HIRAGANA LETTER BE
  U + 307 A  # HIRAGANA LETTER PE
  U + 307 B  # HIRAGANA LETTER HO
  U + 307 C  # HIRAGANA LETTER BO
  U + 307 D  # HIRAGANA LETTER PO
  U + 307 E  # HIRAGANA LETTER MA
  U + 307 F  # HIRAGANA LETTER MI
  U + 3080  # HIRAGANA LETTER MU
  U + 3081  # HIRAGANA LETTER ME
  U + 3082  # HIRAGANA LETTER MO
  U + 3083  # HIRAGANA LETTER SMALL YA
  U + 3084  # HIRAGANA LETTER YA
  U + 3085  # HIRAGANA LETTER SMALL YU
  U + 3086  # HIRAGANA LETTER YU
  U + 3087  # HIRAGANA LETTER SMALL YO
  U + 3088  # HIRAGANA LETTER YO
  U + 3089  # HIRAGANA LETTER RA
  U + 308 A  # HIRAGANA LETTER RI
  U + 308 B  # HIRAGANA LETTER RU
  U + 308 C  # HIRAGANA LETTER RE
  U + 308 D  # HIRAGANA LETTER RO
  U + 308 E  # HIRAGANA LETTER SMALL WA
  U + 308 F  # HIRAGANA LETTER WA
  U + 3090  # HIRAGANA LETTER WI
  U + 3091  # HIRAGANA LETTER WE
  U + 3092  # HIRAGANA LETTER WO
  U + 3093  # HIRAGANA LETTER N
  U + 3094  # HIRAGANA LETTER VU
  U + 3095  # HIRAGANA LETTER SMALL KA
  U + 3096  # HIRAGANA LETTER SMALL KE
  U + 3099  # COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK
  U + 309 A  # COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  U + 309 B  # KATAKANA-HIRAGANA VOICED SOUND MARK
  U + 309 C  # KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  U + 309 D  # HIRAGANA ITERATION MARK
  U + 309 E  # HIRAGANA VOICED ITERATION MARK
  U + 309 F  # HIRAGANA DIGRAPH YORI

  # Box Drawing (Essential for TUI)
  U + 2500  # BOX DRAWINGS LIGHT HORIZONTAL
  U + 2501  # BOX DRAWINGS HEAVY HORIZONTAL
  U + 2502  # BOX DRAWINGS LIGHT VERTICAL
  U + 2503  # BOX DRAWINGS HEAVY VERTICAL
  U + 2504  # BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  U + 2505  # BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
  U + 2506  # BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
  U + 2507  # BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
  U + 2508  # BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
  U + 2509  # BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
  U + 250 A  # BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
  U + 250 B  # BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
  U + 250 C  # BOX DRAWINGS LIGHT DOWN AND RIGHT
  U + 250 D  # BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
  U + 250 E  # BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
  U + 250 F  # BOX DRAWINGS HEAVY DOWN AND RIGHT
  U + 2510  # BOX DRAWINGS LIGHT DOWN AND LEFT
  U + 2511  # BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
  U + 2512  # BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
  U + 2513  # BOX DRAWINGS HEAVY DOWN AND LEFT
  U + 2514  # BOX DRAWINGS LIGHT UP AND RIGHT
  U + 2515  # BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
  U + 2516  # BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
  U + 2517  # BOX DRAWINGS HEAVY UP AND RIGHT
  U + 2518  # BOX DRAWINGS LIGHT UP AND LEFT
  U + 2519  # BOX DRAWINGS UP LIGHT AND LEFT HEAVY
  U + 251 A  # BOX DRAWINGS UP HEAVY AND LEFT LIGHT
  U + 251 B  # BOX DRAWINGS HEAVY UP AND LEFT
  U + 251 C  # BOX DRAWINGS LIGHT VERTICAL AND RIGHT
  U + 251 D  # BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY

  # Part 4 - Katakana and Beginning of Kanji
  # Katakana
  U + 30 A1  # KATAKANA LETTER SMALL A
  U + 30 A2  # KATAKANA LETTER A
  U + 30 A3  # KATAKANA LETTER SMALL I
  U + 30 A4  # KATAKANA LETTER I
  U + 30 A5  # KATAKANA LETTER SMALL U
  U + 30 A6  # KATAKANA LETTER U
  U + 30 A7  # KATAKANA LETTER SMALL E
  U + 30 A8  # KATAKANA LETTER E
  U + 30 A9  # KATAKANA LETTER SMALL O
  U + 30 AA  # KATAKANA LETTER O
  U + 30 AB  # KATAKANA LETTER KA
  U + 30 AC  # KATAKANA LETTER GA
  U + 30 AD  # KATAKANA LETTER KI
  U + 30 AE  # KATAKANA LETTER GI
  U + 30 AF  # KATAKANA LETTER KU
  U + 30 B0  # KATAKANA LETTER GU
  U + 30 B1  # KATAKANA LETTER KE
  U + 30 B2  # KATAKANA LETTER GE
  U + 30 B3  # KATAKANA LETTER KO
  U + 30 B4  # KATAKANA LETTER GO
  U + 30 B5  # KATAKANA LETTER SA
  U + 30 B6  # KATAKANA LETTER ZA
  U + 30 B7  # KATAKANA LETTER SI
  U + 30 B8  # KATAKANA LETTER ZI
  U + 30 B9  # KATAKANA LETTER SU
  U + 30 BA  # KATAKANA LETTER ZU
  U + 30 BB  # KATAKANA LETTER SE
  U + 30 BC  # KATAKANA LETTER ZE
  U + 30 BD  # KATAKANA LETTER SO
  U + 30 BE  # KATAKANA LETTER ZO
  U + 30 BF  # KATAKANA LETTER TA
  U + 30 C0  # KATAKANA LETTER DA
  U + 30 C1  # KATAKANA LETTER TI
  U + 30 C2  # KATAKANA LETTER DI
  U + 30 C3  # KATAKANA LETTER SMALL TU
  U + 30 C4  # KATAKANA LETTER TU
  U + 30 C5  # KATAKANA LETTER DU
  U + 30 C6  # KATAKANA LETTER TE
  U + 30 C7  # KATAKANA LETTER DE
  U + 30 C8  # KATAKANA LETTER TO
  U + 30 C9  # KATAKANA LETTER DO
  U + 30 CA  # KATAKANA LETTER NA
  U + 30 CB  # KATAKANA LETTER NI
  U + 30 CC  # KATAKANA LETTER NU
  U + 30 CD  # KATAKANA LETTER NE
  U + 30 CE  # KATAKANA LETTER NO
  U + 30 CF  # KATAKANA LETTER HA
  U + 30 D0  # KATAKANA LETTER BA
  U + 30 D1  # KATAKANA LETTER PA
  U + 30 D2  # KATAKANA LETTER HI
  U + 30 D3  # KATAKANA LETTER BI
  U + 30 D4  # KATAKANA LETTER PI
  U + 30 D5  # KATAKANA LETTER HU
  U + 30 D6  # KATAKANA LETTER BU
  U + 30 D7  # KATAKANA LETTER PU
  U + 30 D8  # KATAKANA LETTER HE
  U + 30 D9  # KATAKANA LETTER BE
  U + 30 DA  # KATAKANA LETTER PE
  U + 30 DB  # KATAKANA LETTER HO
  U + 30 DC  # KATAKANA LETTER BO
  U + 30 DD  # KATAKANA LETTER PO
  U + 30 DE  # KATAKANA LETTER MA
  U + 30 DF  # KATAKANA LETTER MI
  U + 30 E0  # KATAKANA LETTER MU
  U + 30 E1  # KATAKANA LETTER ME
  U + 30 E2  # KATAKANA LETTER MO
  U + 30 E3  # KATAKANA LETTER SMALL YA
  U + 30 E4  # KATAKANA LETTER YA
  U + 30 E5  # KATAKANA LETTER SMALL YU
  U + 30 E6  # KATAKANA LETTER YU
  U + 30 E7  # KATAKANA LETTER SMALL YO
  U + 30 E8  # KATAKANA LETTER YO
  U + 30 E9  # KATAKANA LETTER RA
  U + 30 EA  # KATAKANA LETTER RI
  U + 30 EB  # KATAKANA LETTER RU
  U + 30 EC  # KATAKANA LETTER RE
  U + 30 ED  # KATAKANA LETTER RO
  U + 30 EE  # KATAKANA LETTER SMALL WA
  U + 30 EF  # KATAKANA LETTER WA
  U + 30 F0  # KATAKANA LETTER WI
  U + 30 F1  # KATAKANA LETTER WE
  U + 30 F2  # KATAKANA LETTER WO
  U + 30 F3  # KATAKANA LETTER N
  U + 30 F4  # KATAKANA LETTER VU
  U + 30 F5  # KATAKANA LETTER SMALL KA
  U + 30 F6  # KATAKANA LETTER SMALL KE
  U + 30 FC  # KATAKANA-HIRAGANA PROLONGED SOUND MARK
  U + 30 FD  # KATAKANA ITERATION MARK
  U + 30 FE  # KATAKANA VOICED ITERATION MARK

  # Beginning Grade 1 Kanji (Most Basic/Common)
  U + 4 E00  # KANJI ONE, HORIZONTAL LINE
  U + 4 E03  # KANJI SEVEN
  U + 4 E09  # KANJI THREE
  U + 4 E0A  # KANJI ABOVE, UP
  U + 4 E0B  # KANJI BELOW, DOWN
  U + 4 E2D  # KANJI MIDDLE, INSIDE
  U + 4 E5D  # KANJI NINE
  U + 4 E8C  # KANJI TWO
  U + 4 EBA  # KANJI PERSON
  U + 4 E94  # KANJI FIVE
  U + 516 B  # KANJI EIGHT
  U + 5186  # KANJI YEN, CIRCLE
  U + 51 AC  # KANJI WINTER
  U + 520 A  # KANJI PUBLICATION
  U + 5343  # KANJI THOUSAND
  U + 53 CB  # KANJI FRIEND
  U + 53 E3  # KANJI MOUTH
  U + 53 F3  # KANJI RIGHT
  U + 5408  # KANJI FIT, JOIN
  U + 5409  # KANJI LUCK, FORTUNE

  # Part 5 - Continuing Grade 1 Kanji and Essential Compounds
  # More Grade 1 Kanji
  U + 5915  # KANJI EVENING
  U + 5927  # KANJI BIG, LARGE
  U + 5929  # KANJI HEAVEN, SKY
  U + 5973  # KANJI WOMAN
  U + 5 B50  # KANJI CHILD
  U + 5 B57  # KANJI CHARACTER
  U + 5 B66  # KANJI STUDY, LEARNING
  U + 5 DE6  # KANJI LEFT
  U + 5 E74  # KANJI YEAR
  U + 5 E7C  # KANJI INFANCY
  U + 5 EAB  # KANJI STOREHOUSE
  U + 5 F13  # KANJI BOW
  U + 5 F31  # KANJI WEAK
  U + 5 F37  # KANJI STRONG
  U + 5 F53  # KANJI HIT, RIGHT
  U + 5 F97  # KANJI GAIN, GET
  U + 601 D  # KANJI THINK
  U + 6238  # KANJI DOOR
  U + 624 B  # KANJI HAND
  U + 6559  # KANJI TEACH
  U + 6587  # KANJI LITERATURE
  U + 65 E5  # KANJI DAY, SUN
  U + 65 E9  # KANJI EARLY
  U + 6625  # KANJI SPRING
  U + 6642  # KANJI TIME, HOUR
  U + 666 E  # KANJI UNIVERSAL
  U + 6674  # KANJI CLEAR WEATHER
  U + 6708  # KANJI MONTH, MOON
  U + 6728  # KANJI TREE, WOOD
  U + 6751  # KANJI VILLAGE
  U + 6765  # KANJI COME
  U + 6771  # KANJI EAST
  U + 6797  # KANJI FOREST
  U + 679 C  # KANJI FRUIT
  U + 6821  # KANJI SCHOOL
  U + 683 C  # KANJI STANDARD
  U + 6885  # KANJI PLUM
  U + 691 C  # KANJI EXAMINE
  U + 697 D  # KANJI COMFORT, EASE
  U + 6 A2A  # KANJI HORIZONTAL
  U + 6 B4C  # KANJI SONG
  U + 6 B63  # KANJI CORRECT
  U + 6 B69  # KANJI WALK
  U + 6 C17  # KANJI SPIRIT
  U + 6 C34  # KANJI WATER
  U + 6 C7D  # KANJI STEAM, VAPOR
  U + 6 D77  # KANJI SEA
  U + 706 B  # KANJI FIRE
  U + 722 A  # KANJI CLAW
  U + 7236  # KANJI FATHER
  U + 7267  # KANJI SHEPHERD
  U + 7269  # KANJI THING
  U + 72 AC  # KANJI DOG
  U + 7389  # KANJI JADE
  U + 738 B  # KANJI KING
  U + 73 ED  # KANJI CLASS, GROUP
  U + 751 F  # KANJI LIFE
  U + 7528  # KANJI USE
  U + 753 B  # KANJI PICTURE
  U + 756 A  # KANJI NUMBER, ORDER
  U + 767 D  # KANJI WHITE
  U + 76 AE  # KANJI SKIN
  U + 76 EE  # KANJI EYE
  U + 77 E2  # KANJI ARROW
  U + 77 E5  # KANJI KNOW
  U + 77 F3  # KANJI STONE
  U + 793 E  # KANJI SOCIETY
  U + 795 D  # KANJI CELEBRATE
  U + 79 CB  # KANJI AUTUMN
  U + 7 A2E  # KANJI SEED, KIND
  U + 7 A7A  # KANJI EMPTY, SKY
  U + 7 ACB  # KANJI STAND
  U + 7 AF9  # KANJI BAMBOO
  U + 7 B11  # KANJI LAUGH
  U + 7 B2C  # KANJI ORDINAL NUMBER
  U + 7 B49  # KANJI EQUAL
  U + 7 B54  # KANJI ANSWER
  U + 7 BAD  # KANJI ARROW
  U + 7 C73  # KANJI RICE
  U + 7 CF8  # KANJI THREAD
  U + 7 D19  # KANJI PAPER
  U + 7 D30  # KANJI THIN
  U + 7 D44  # KANJI GROUP
  U + 7 DB1  # KANJI RULE
  U + 7 DCF  # KANJI GENERAL
  U + 7 DDA  # KANJI LINE
  U + 7 F8E  # KANJI BEAUTY
  U + 7 FBD  # KANJI FEATHER
  U + 8003  # KANJI CONSIDER
  U + 8005  # KANJI PERSON
  U + 8033  # KANJI EAR
  U + 8089  # KANJI MEAT
  U + 808 C  # KANJI SKIN
  U + 80 A1  # KANJI STOCK
  U + 80 B2  # KANJI NURTURE
  U + 8133  # KANJI BRAIN
  U + 8170  # KANJI WAIST
  U + 81 EA  # KANJI SELF
  U + 8239  # KANJI SHIP
  U + 826 F  # KANJI GOOD
  U + 82 B1  # KANJI FLOWER
  U + 82 F1  # KANJI ENGLAND, HERO
  U + 8336  # KANJI TEA
  U + 8349  # KANJI GRASS
  U + 83 DC  # KANJI VEGETABLE
  U + 843 D  # KANJI FALL
  U + 85 AC  # KANJI MEDICINE

  # Part 6 - Common Use Kanji (Continuing Grade 1 and 2)
  # Essential Everyday Kanji
  U + 866 B  # KANJI INSECT
  U + 8840  # KANJI BLOOD
  U + 884 C  # KANJI GO
  U + 8863  # KANJI CLOTHING
  U + 897 F  # KANJI WEST
  U + 89 AA  # KANJI PARENT
  U + 89 D2  # KANJI ANGLE, CORNER
  U + 8 A00  # KANJI SAY
  U + 8 A08  # KANJI MEASURE
  U + 8 A18  # KANJI RECORD
  U + 8 A71  # KANJI TALK
  U + 8 A8C  # KANJI MAGAZINE
  U + 8 A9E  # KANJI LANGUAGE
  U + 8 AAD  # KANJI READ
  U + 8 AB0  # KANJI WHO
  U + 8 ABF  # KANJI TONE, INVESTIGATE
  U + 8 AC7  # KANJI DISCUSS
  U + 8 B66  # KANJI ADMONISH
  U + 8 C37  # KANJI VALLEY
  U + 8 C46  # KANJI BEANS
  U + 8 C9D  # KANJI SHELL
  U + 8 CA8  # KANJI GOODS
  U + 8 CB4  # KANJI PRECIOUS
  U + 8 CBB  # KANJI EXPENSE
  U + 8 CD3  # KANJI VISITOR
  U + 8 D64  # KANJI RED
  U + 8 D70  # KANJI RUN
  U + 8 DB3  # KANJI FOOT, SUFFICIENT
  U + 8 EAB  # KANJI BODY
  U + 8 ECA  # KANJI VEHICLE
  U + 8 ECD  # KANJI ARMY
  U + 8 EE2  # KANJI REVOLVE
  U + 8 EFD  # KANJI LIGHT
  U + 8 F9B  # KANJI SPICY
  U + 8 FB0  # KANJI DRAGON
  U + 8 FB1  # KANJI HUMILIATE
  U + 8 FCE  # KANJI WELCOME
  U + 8 FD1  # KANJI NEAR
  U + 8 FD4  # KANJI RETURN
  U + 8 FFD  # KANJI FOLLOW
  U + 9000  # KANJI RETREAT
  U + 9001  # KANJI SEND
  U + 9006  # KANJI REVERSE
  U + 9032  # KANJI ADVANCE
  U + 9038  # KANJI SURPASS
  U + 9053  # KANJI ROAD, WAY
  U + 9060  # KANJI DISTANT
  U + 9078  # KANJI CHOOSE
  U + 90 A3  # KANJI WHAT
  U + 90 E8  # KANJI PART, SECTION
  U + 90 FD  # KANJI CAPITAL
  U + 91 CC  # KANJI VILLAGE, MILE
  U + 91 CD  # KANJI HEAVY
  U + 91 CE  # KANJI FIELD
  U + 91 D1  # KANJI GOLD, METAL
  U + 9234  # KANJI BELL
  U + 9280  # KANJI SILVER
  U + 9285  # KANJI COPPER
  U + 92 AD  # KANJI COIN
  U + 92 FC  # KANJI STEEL
  U + 9577  # KANJI LONG, LEADER
  U + 9580  # KANJI GATE
  U + 9589  # KANJI CLOSE
  U + 958 B  # KANJI OPEN
  U + 9592  # KANJI LEISURE
  U + 9593  # KANJI INTERVAL
  U + 95 A2  # KANJI CONNECTION
  U + 95 B2  # KANJI READ
  U + 961 C  # KANJI MOUND
  U + 9632  # KANJI PREVENT
  U + 963 F  # KANJI AFRICA
  U + 9644  # KANJI ATTACH
  U + 9662  # KANJI INSTITUTION
  U + 966 A  # KANJI ACCOMPANY
  U + 9678  # KANJI LAND
  U + 967 D  # KANJI SUN, POSITIVE
  U + 96 E8  # KANJI RAIN
  U + 96 EA  # KANJI SNOW
  U + 96 F2  # KANJI CLOUD
  U + 96 FB  # KANJI ELECTRICITY
  U + 9752  # KANJI BLUE
  U + 9759  # KANJI QUIET
  U + 975 E  # KANJI NOT
  U + 9762  # KANJI FACE
  U + 9769  # KANJI LEATHER
  U + 97 D3  # KANJI KOREA
  U + 97 F3  # KANJI SOUND
  U + 9802  # KANJI SUMMIT
  U + 9806  # KANJI OBEY
  U + 9808  # KANJI MUST
  U + 9810  # KANJI BEFOREHAND
  U + 982 D  # KANJI HEAD
  U + 9854  # KANJI FACE
  U + 98 A8  # KANJI WIND
  U + 98 DB  # KANJI FLY
  U + 98 DF  # KANJI FOOD, EAT
  U + 98 FC  # KANJI FEED
  U + 9928  # KANJI BUILDING
  U + 9996  # KANJI HEAD
  U + 99 AC  # KANJI HORSE
  U + 99 C5  # KANJI STATION
  U + 99 D0  # KANJI STAY
  U + 9 A13  # KANJI VERIFY
  U + 9 AA8  # KANJI BONE
  U + 9 AD8  # KANJI HIGH

  # Part 7 - Continuing Essential Kanji and Compounds
  # Common Business/Technical Kanji
  U + 9 B3C  # KANJI GHOST, DEVIL
  U + 9 B42  # KANJI SOUL
  U + 9 B45  # KANJI CHARM
  U + 9 B54  # KANJI DEMON
  U + 9 CE5  # KANJI BIRD
  U + 9 CF4  # KANJI CRY, SOUND
  U + 9 D8F  # KANJI PHOENIX
  U + 9 E7F  # KANJI DEER
  U + 9 EA6  # KANJI WHEAT
  U + 9 EC4  # KANJI YELLOW
  U + 9 ED2  # KANJI BLACK
  U + 9 F13  # KANJI DRUM
  U + 9 F3B  # KANJI NOSE
  U + 9 F62  # KANJI AGE

  # Technical Computing Kanji
  U + 5024  # KANJI VALUE
  U + 5 B58  # KANJI EXIST
  U + 60 C5  # KANJI FEELINGS, CIRCUMSTANCES
  U + 5831  # KANJI REPORT
  U + 5 B9A  # KANJI DETERMINE
  U + 5316  # KANJI CHANGE
  U + 7 A0B  # KANJI PROCESS
  U + 5 F0F  # KANJI STYLE
  U + 6570  # KANJI NUMBER
  U + 5024  # KANJI VALUE
  U + 5909  # KANJI CHANGE
  U + 6 A5F  # KANJI MACHINE
  U + 80 FD  # KANJI ABILITY
  U + 5 B9F  # KANJI REALITY
  U + 884 C  # KANJI GOING
  U + 52 D5  # KANJI MOVE
  U + 4 F5C  # KANJI MAKE
  U + 6210  # KANJI BECOME
  U + 578 B  # KANJI TYPE
  U + 5165  # KANJI ENTER
  U + 529 B  # KANJI POWER
  U + 51 FA  # KANJI EXIT
  U + 4 F7F  # KANJI USE
  U + 7528  # KANJI UTILIZE
  U + 5 B8C  # KANJI COMPLETE
  U + 4 E86  # KANJI FINISH
  U + 958 B  # KANJI OPEN
  U + 59 CB  # KANJI BEGIN
  U + 7 D42  # KANJI END
  U + 6 E08  # KANJI SETTLE

  # Common Programming Terms
  U + 914 D  # KANJI DISTRIBUTE (ARRAY)
  U + 5217  # KANJI LINE UP (LIST)
  U + 5 C0E  # KANJI GUIDE (POINTER)
  U + 5909  # KANJI CHANGE (VARIABLE)
  U + 6570  # KANJI NUMBER (NUMERIC)
  U + 5024  # KANJI VALUE
  U + 578 B  # KANJI TYPE
  U + 6587  # KANJI SENTENCE (STRING)
  U + 5 B57  # KANJI CHARACTER
  U + 5 F0F  # KANJI EXPRESSION
  U + 6 A21  # KANJI PATTERN
  U + 7 BC4  # KANJI EXAMPLE
  U + 5 F35  # KANJI EXTEND
  U + 7 D50  # KANJI TIE (BIND)
  U + 679 C  # KANJI RESULT
  U + 4 EF6  # KANJI MATTER (CASE)
  U + 8 A08  # KANJI MEASURE (CALCULATE)
  U + 7 B97  # KANJI CALCULATE
  U + 5236  # KANJI SYSTEM
  U + 5 FA1  # KANJI HONORABLE (CONTROL)

  # Essential Radicals (Important for compound understanding)
  U + 4 E00  # HORIZONTAL LINE
  U + 4 E28  # VERTICAL LINE
  U + 4 E36  # DOT
  U + 4 E3F  # SLASH
  U + 4 E59  # SECOND
  U + 4 E85  # TABLE
  U + 4 EA0  # LID
  U + 4 EBB  # PERSON
  U + 513 F  # LEGS
  U + 5165  # ENTER
  U + 516 B  # EIGHT
  U + 516 D  # SIX
  U + 5182  # ENCLOSURE
  U + 5196  # PRIVATE
  U + 51 AB  # ICE
  U + 51 E0  # TABLE
  U + 51 F5  # PRIVATE
  U + 5200  # KNIFE
  U + 5202  # SWORD
  U + 5315  # LONG
  U + 531 A  # EVENING
  U + 5338  # SHIELD
  U + 5341  # TEN
  U + 535 C  # DIVINATION
  U + 5369  # FORMER
  U + 5382  # CLIFF
  U + 53 B6  # SHORT THREAD
  U + 53 C8  # AGAIN
  U + 53 CA  # AND
  U + 53 E3  # MOUTH
  U + 56 D7  # VILLAGE
  U + 571 F  # EARTH
  U + 58 EB  # SCHOLAR
  U + 5902  # EARLY
  U + 590 A  # SUMMER
  U + 5915  # EVENING
  U + 5927  # BIG
  U + 5973  # WOMAN
  U + 5 B50  # CHILD
  U + 5 B80  # ROOF
  U + 5 BF8  # INCH
  U + 5 C0F  # SMALL
  U + 5 C22  # SPECIALTY
  U + 5 C38  # CORPSE
  U + 5 C6E  # CAVE
  U + 5 DDB  # CLIFF
  U + 5 DE5  # WORK
  U + 5 DF1  # ONESELF
  U + 5 DFE  # TOWEL
  U + 5 E72  # DRY
  U + 5 E7F  # WIDE
  U + 5 EF4  # CAVE
  U + 5 F13  # BOW
  U + 5 F50  # CLOTH
  U + 5 F61  # SPEAR
  U + 5 F73  # LONG TIME
  U + 5 FC3  # HEART
  U + 5 FC4  # COMPARE
  U + 6208  # SPEAR
  U + 6238  # DOOR
  U + 624 C  # HAND
  U + 6253  # STRIKE
  U + 6279  # CRITICIZE
  U + 62 D0  # BIG
  U + 62 D1  # STAMP
  U + 62 FF  # TAKE
  U + 6325  # WAVE

  # Part 8 - More Radicals and Specialized Characters
  # Additional Important Radicals
  U + 6355  # KANJI CATCH
  U + 6367  # KANJI RESPECT
  U + 63 A0  # KANJI PICK UP
  U + 63 A2  # KANJI SEARCH
  U + 63 A7  # KANJI CONTROL
  U + 63 A9  # KANJI HIDE
  U + 63 AA  # KANJI MEASURE
  U + 63 B2  # KANJI RAISE
  U + 63 CF  # KANJI DESCRIBE
  U + 63 D0  # KANJI PROPOSE
  U + 63 DB  # KANJI EXCHANGE
  U + 63 E1  # KANJI GRIP
  U + 63 EE  # KANJI BRANDISH
  U + 63 F4  # KANJI AID
  U + 6406  # KANJI EMBRACE
  U + 640 D  # KANJI LOSS
  U + 640 F  # KANJI GROPE
  U + 6413  # KANJI INVESTIGATE
  U + 6416  # KANJI SHAKE
  U + 6417  # KANJI POUND

  # Scientific and Mathematical Kanji
  U + 6570  # KANJI NUMBER
  U + 6575  # KANJI ENEMY
  U + 6577  # KANJI SPREAD
  U + 6578  # KANJI COUNT
  U + 6599  # KANJI FEE
  U + 65 B0  # KANJI NEW
  U + 65 B9  # KANJI DIRECTION
  U + 65 BD  # KANJI IMPLEMENT
  U + 65 C5  # KANJI TRIP
  U + 65 CF  # KANJI TRIBE
  U + 65 E5  # KANJI DAY
  U + 65 E7  # KANJI OLD
  U + 65 E8  # KANJI PURPORT
  U + 65 E9  # KANJI EARLY
  U + 65 EC  # KANJI DAYBREAK

  # Modern Technical Terms
  U + 6642  # KANJI TIME
  U + 6643  # KANJI DARK
  U + 6649  # KANJI CLEAR
  U + 664 B  # KANJI ADVANCE
  U + 664 C  # KANJI RISE
  U + 664 F  # KANJI DARK
  U + 6652  # KANJI DRY IN SUN
  U + 6674  # KANJI CLEAR WEATHER
  U + 6676  # KANJI CRYSTAL
  U + 667 A  # KANJI WISDOM
  U + 6691  # KANJI HOT
  U + 6696  # KANJI WARM
  U + 6697  # KANJI DARK
  U + 66 A6  # KANJI CALENDAR
  U + 66 AB  # KANJI TEMPORARY
  U + 66 AE  # KANJI TWILIGHT
  U + 66 B4  # KANJI VIOLENT
  U + 66 C7  # KANJI DARK
  U + 66 D6  # KANJI DAWN
  U + 66 DC  # KANJI DAY OF WEEK
  U + 66 F2  # KANJI CURVE
  U + 66 F3  # KANJI BRIGHT
  U + 66 F4  # KANJI CHANGE
  U + 66 F8  # KANJI WRITE
  U + 66 F9  # KANJI MILITARY
  U + 66 FC  # KANJI BARBARIAN
  U + 66 FE  # KANJI BEFORE
  U + 66 FF  # KANJI REPLACE

  # Programming and Technology
  U + 6700  # KANJI MOST
  U + 6708  # KANJI MONTH
  U + 6709  # KANJI POSSESS
  U + 670 B  # KANJI COMPANION
  U + 670 D  # KANJI CLOTHING
  U + 6717  # KANJI CLEAR
  U + 671 B  # KANJI HOPE
  U + 671 D  # KANJI MORNING
  U + 671 F  # KANJI PERIOD
  U + 6728  # KANJI TREE
  U + 672 A  # KANJI NOT YET
  U + 672 B  # KANJI END
  U + 672 C  # KANJI BOOK
  U + 672 D  # KANJI TAG
  U + 672 E  # KANJI BRUSH
  U + 6731  # KANJI VERMILLION
  U + 6734  # KANJI SIMPLE
  U + 673 A  # KANJI MACHINE
  U + 673 D  # KANJI BRANCH

  # Half-width Katakana
  U + FF61  # HALFWIDTH IDEOGRAPHIC FULL STOP ｡
  U + FF62  # HALFWIDTH LEFT CORNER BRACKET ｢
  U + FF63  # HALFWIDTH RIGHT CORNER BRACKET ｣
  U + FF64  # HALFWIDTH IDEOGRAPHIC COMMA ､
  U + FF65  # HALFWIDTH KATAKANA MIDDLE DOT ･
  U + FF71  # HALFWIDTH KATAKANA LETTER A ｱ
  U + FF72  # HALFWIDTH KATAKANA LETTER I ｲ
  U + FF73  # HALFWIDTH KATAKANA LETTER U ｳ
  U + FF74  # HALFWIDTH KATAKANA LETTER E ｴ
  U + FF75  # HALFWIDTH KATAKANA LETTER O ｵ
  U + FF76  # HALFWIDTH KATAKANA LETTER KA ｶ
  U + FF77  # HALFWIDTH KATAKANA LETTER KI ｷ
  U + FF78  # HALFWIDTH KATAKANA LETTER KU ｸ
  U + FF79  # HALFWIDTH KATAKANA LETTER KE ｹ
  U + FF7A  # HALFWIDTH KATAKANA LETTER KO ｺ
  U + FF7B  # HALFWIDTH KATAKANA LETTER SA ｻ
  U + FF7C  # HALFWIDTH KATAKANA LETTER SI ｼ
  U + FF7D  # HALFWIDTH KATAKANA LETTER SU ｽ
  U + FF7E  # HALFWIDTH KATAKANA LETTER SE ｾ
  U + FF7F  # HALFWIDTH KATAKANA LETTER SO ｿ
  U + FF80  # HALFWIDTH KATAKANA LETTER TA ﾀ
  U + FF81  # HALFWIDTH KATAKANA LETTER TI ﾁ
  U + FF82  # HALFWIDTH KATAKANA LETTER TU ﾂ
  U + FF83  # HALFWIDTH KATAKANA LETTER TE ﾃ
  U + FF84  # HALFWIDTH KATAKANA LETTER TO ﾄ
  U + FF85  # HALFWIDTH KATAKANA LETTER NA ﾅ
  U + FF86  # HALFWIDTH KATAKANA LETTER NI ﾆ
  U + FF87  # HALFWIDTH KATAKANA LETTER NU ﾇ
  U + FF88  # HALFWIDTH KATAKANA LETTER NE ﾈ
  U + FF89  # HALFWIDTH KATAKANA LETTER NO ﾉ
  U + FF8A  # HALFWIDTH KATAKANA LETTER HA ﾊ
  U + FF8B  # HALFWIDTH KATAKANA LETTER HI ﾋ
  U + FF8C  # HALFWIDTH KATAKANA LETTER HU ﾌ
  U + FF8D  # HALFWIDTH KATAKANA LETTER HE ﾍ
  U + FF8E  # HALFWIDTH KATAKANA LETTER HO ﾎ
  U + FF8F  # HALFWIDTH KATAKANA LETTER MA ﾏ
  U + FF90  # HALFWIDTH KATAKANA LETTER MI ﾐ
  U + FF91  # HALFWIDTH KATAKANA LETTER MU ﾑ
  U + FF92  # HALFWIDTH KATAKANA LETTER ME ﾒ
  U + FF93  # HALFWIDTH KATAKANA LETTER MO ﾓ
  U + FF94  # HALFWIDTH KATAKANA LETTER YA ﾔ
  U + FF95  # HALFWIDTH KATAKANA LETTER YU ﾕ
  U + FF96  # HALFWIDTH KATAKANA LETTER YO ﾖ
  U + FF97  # HALFWIDTH KATAKANA LETTER RA ﾗ
  U + FF98  # HALFWIDTH KATAKANA LETTER RI ﾘ
  U + FF99  # HALFWIDTH KATAKANA LETTER RU ﾙ
  U + FF9A  # HALFWIDTH KATAKANA LETTER RE ﾚ
  U + FF9B  # HALFWIDTH KATAKANA LETTER RO ﾛ
  U + FF9C  # HALFWIDTH KATAKANA LETTER WA ﾜ
  U + FF9D  # HALFWIDTH KATAKANA LETTER N  ﾝ
  U + FF66  # HALFWIDTH KATAKANA LETTER WO ｦ
  U + FF67  # HALFWIDTH KATAKANA LETTER SMALL A ｧ
  U + FF68  # HALFWIDTH KATAKANA LETTER SMALL I ｨ
  U + FF69  # HALFWIDTH KATAKANA LETTER SMALL U ｩ
  U + FF6A  # HALFWIDTH KATAKANA LETTER SMALL E ｪ
  U + FF6B  # HALFWIDTH KATAKANA LETTER SMALL O ｫ
  U + FF6C  # HALFWIDTH KATAKANA LETTER SMALL YA ｬ
  U + FF6D  # HALFWIDTH KATAKANA LETTER SMALL YU ｭ
  U + FF6E  # HALFWIDTH KATAKANA LETTER SMALL YO ｮ
  U + FF6F  # HALFWIDTH KATAKANA LETTER SMALL TU ｯ
  U + FF9E  # HALFWIDTH KATAKANA VOICED SOUND MARK ﾞ
  U + FF9F  # HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK ﾟ
